name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Installing dependencies
        run: npm install
      - name: Build
        run: npm run prepack
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: lib
          path: lib

  release:
    name: Download dist and release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Installing dependencies
        run: npm install
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: lib
          path: lib
      - name: Display dirs
        run: ls -R
      - name: Release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
